version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: . #we want build a docker file. here,  we're referring to the file in the current dir
    ports:
      - '80:3000'
    links: #linking app service(or container) with mongo
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
